# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0026_run_exclude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='run',
            options={'ordering': ['-task_in_progress', '-date_started'], 'permissions': (('view_run', 'View run'),)},
        ),
        migrations.AlterField(
            model_name='run',
            name='current_task',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='run',
            name='exclude',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='tasks',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterUniqueTogether(
            name='calculationfieldtemplate',
            unique_together=set([('template', 'label')]),
        ),
    ]
