# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-28 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0027_auto_20170918_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculationfieldtemplate',
            options={'ordering': ['-id'], 'permissions': (('view_calculationfieldtemplate', 'View calculation field template'),)},
        ),
        migrations.AlterModelOptions(
            name='inputfieldtemplate',
            options={'ordering': ['-id'], 'permissions': (('view_inputfieldtemplate', 'View input field template'),)},
        ),
        migrations.AlterModelOptions(
            name='outputfieldtemplate',
            options={'ordering': ['-id'], 'permissions': (('view_outputfieldtemplate', 'View output field template'),)},
        ),
        migrations.AlterModelOptions(
            name='stepfieldproperty',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='stepfieldtemplate',
            options={'ordering': ['-id'], 'permissions': (('view_stepfieldtemplate', 'View step field template'),)},
        ),
        migrations.AlterModelOptions(
            name='tasktemplate',
            options={'ordering': ['-id'], 'permissions': (('view_tasktemplate', 'View workflow task template'),)},
        ),
        migrations.AlterModelOptions(
            name='variablefieldtemplate',
            options={'ordering': ['-id'], 'permissions': (('view_variablefieldtemplate', 'View variable field template'),)},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={'ordering': ['-id'], 'permissions': (('view_workflow', 'View workflow'),)},
        ),
        migrations.AddField(
            model_name='inputfieldtemplate',
            name='auto_find_in_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stepfieldproperty',
            name='measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.AmountMeasure'),
        ),
    ]
