# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-06 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0028_auto_20180228_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='product_input_not_required',
            field=models.BooleanField(default=False),
        ),
    ]
