# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-06 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0029_tasktemplate_product_input_not_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktemplate',
            name='product_input',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_input', to='inventory.ItemType'),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='product_input_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='product_input_measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.AmountMeasure'),
        ),
    ]
