# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-08 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0030_auto_20180306_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepfieldproperty',
            name='measure_not_required',
            field=models.BooleanField(default=False),
        ),
    ]
