# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 13:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
