# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-01 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_equipmentreservation_reservation_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentreservation',
            options={'ordering': ['start']},
        ),
    ]
