# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20161111_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmproject',
            name='status',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
