# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-05 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20180301_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtransfer',
            name='amount_available',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='itemtransfer',
            name='amount_taken',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='itemtransfer',
            name='amount_to_take',
            field=models.FloatField(default=0),
        ),
    ]
