# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 13:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_product_sbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='links',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
