# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20170713_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'permissions': (('view_projectstatus', 'View project status'),),
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['identifier'], 'permissions': (('view_project', 'View project'),)},
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectStatus'),
        ),
    ]
