# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 14:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20170818_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
