# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-01 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_project_properties'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'permissions': (('view_product', 'View product'),)},
        ),
        migrations.AlterModelOptions(
            name='productstatus',
            options={'ordering': ['-id'], 'permissions': (('view_productstatus', 'View product status'),)},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-identifier'], 'permissions': (('view_project', 'View project'),)},
        ),
        migrations.AlterModelOptions(
            name='projectstatus',
            options={'ordering': ['-id'], 'permissions': (('view_projectstatus', 'View project status'),)},
        ),
    ]
