# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-09 11:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0019_auto_20180301_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadlineExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_deadline', models.DateTimeField()),
                ('extended_on', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('extended_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deadlineextension',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_extensions', to='projects.Project'),
        ),
    ]
