# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-09 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20180309_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deadline_warn',
            field=models.IntegerField(default=7),
        ),
    ]
