# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-14 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_project_deadline_warn'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deadline_status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
