# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-01 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20160920_0844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copyfiledriver',
            options={'ordering': ['-id']},
        ),
    ]
